# Generated by Django 5.2.1 on 2025-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='found_items/photos/'),
        ),
    ]
