# Generated by Django 5.2.1 on 2025-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_founditem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
