# Generated by Django 5.2.1 on 2025-08-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_lostitem_reporter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
