# Generated by Django 5.2.1 on 2025-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0004_lostitem_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='finder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='finder_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='place_found',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
