# Generated by Django 5.2.1 on 2025-08-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0005_alter_founditem_card_last_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='place_lost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
