# Generated by Django 5.2.5 on 2025-08-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0006_alter_lostitem_card_last_four_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lostitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/photos/'),
        ),
    ]
