# Generated by Django 5.2.1 on 2025-09-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0009_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='value',
            field=models.TextField(),
        ),
    ]
