# Generated by Django 5.2.1 on 2025-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0010_alter_systemsettings_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
