# Generated by Django 5.2.1 on 2025-09-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0011_alter_founditem_card_last_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='service_code',
            field=models.CharField(blank=True, help_text='Service code used for validation', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='service_code',
            field=models.CharField(blank=True, help_text='Service code used for validation', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pickuplog',
            name='service_code',
            field=models.CharField(blank=True, help_text='Service code used for validation', max_length=10, null=True),
        ),
    ]
