# Generated by Django 5.2.1 on 2025-09-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0012_founditem_service_code_lostitem_service_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='service_code',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='service_code',
        ),
        migrations.RemoveField(
            model_name='pickuplog',
            name='service_code',
        ),
    ]
