# Generated by Django 5.2.1 on 2025-06-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('General', 'General'), ('Facilities', 'Facilities'), ('Maintenance', 'Maintenance'), ('Security', 'Security'), ('IT', 'IT'), ('Other', 'Other')], default='General', max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('reported_by', models.CharField(max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('key_type', models.CharField(choices=[('Master', 'Master'), ('Access', 'Access'), ('Other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked-out', 'Checked Out'), ('lost', 'Lost')], default='available', max_length=20)),
                ('current_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_holder_type', models.CharField(blank=True, choices=[('staff', 'Staff'), ('member', 'Member'), ('contractor', 'Contractor'), ('visitor', 'Visitor')], max_length=20, null=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
