# Generated by Django 5.2.1 on 2025-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedissue',
            name='reported_by',
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Facilities', 'Facilities'), ('Maintenance', 'Maintenance'), ('Security', 'Security'), ('IT', 'IT'), ('Other', 'Other')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportedissue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
