# Generated by Django 5.2.1 on 2025-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_rename_date_reported_reportedissue_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedissue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
