# Generated by Django 5.2.1 on 2025-06-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_alter_reportedissue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitykey',
            name='key_type',
        ),
        migrations.CreateModel(
            name='KeyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('holder_name', models.CharField(max_length=100)),
                ('holder_type', models.CharField(max_length=20)),
                ('holder_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='extensions.securitykey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
