# Generated by Django 5.2.1 on 2025-06-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0004_remove_securitykey_key_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitykey',
            name='key_type',
            field=models.CharField(choices=[('Master', 'Master'), ('Access', 'Access'), ('Other', 'Other')], default='Access', max_length=20),
        ),
    ]
