# Generated by Django 5.2.1 on 2026-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0005_securitykey_key_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedissue',
            old_name='date_reported',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='securitykey',
            name='current_holder_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
