# Generated by Django 5.2.1 on 2025-06-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_package_picker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
