# Generated by Django 5.2.1 on 2025-08-31 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_package_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_ip', models.CharField(default='192.168.10.173', help_text='Printer IP address', max_length=15)),
                ('printer_port', models.IntegerField(default=9100, help_text='Printer port')),
                ('enable_qr_codes', models.BooleanField(default=True, help_text='Enable QR code generation on receipts')),
                ('default_package_type', models.CharField(choices=[('package', 'Package'), ('document', 'Document'), ('keys', 'keys')], default='package', max_length=10)),
                ('auto_print_on_create', models.BooleanField(default=True, help_text='Automatically print receipt when package is created')),
                ('enable_reprint', models.BooleanField(default=True, help_text='Allow reprinting of package receipts')),
                ('max_reprint_attempts', models.IntegerField(default=3, help_text='Maximum number of reprint attempts')),
                ('notification_email', models.EmailField(blank=True, help_text='Email for notifications', max_length=254, null=True)),
                ('enable_sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications for package updates')),
                ('sms_api_key', models.CharField(blank=True, help_text='SMS API key', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
