# Generated by Django 5.2.1 on 2025-08-31 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed (created, picked, reprinted, etc.)', max_length=50)),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('picked', 'Picked')], max_length=10, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('picked', 'Picked')], max_length=10, null=True)),
                ('performed_by', models.CharField(blank=True, help_text='User who performed the action', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myapp.package')),
            ],
            options={
                'verbose_name': 'Package History',
                'verbose_name_plural': 'Package History',
                'ordering': ['-timestamp'],
            },
        ),
    ]
