# Generated by Django 5.2.1 on 2025-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_packagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dropper_id',
            field=models.CharField(blank=True, help_text='Member number (max 5 characters)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='printer_ip',
            field=models.CharField(default='192.168.10.175', help_text='Printer IP address', max_length=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='dropper_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
