# Generated by Django 5.2.1 on 2025-09-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_package_dropper_id_alter_appsettings_printer_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='dropper_id',
            field=models.CharField(blank=True, help_text='Member number (max 6 characters)', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='picker_id',
            field=models.CharField(blank=True, help_text='Picker member number (max 6 characters)', max_length=20, null=True),
        ),
    ]
