# Generated by Django 5.2.1 on 2025-09-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_package_recipient_id_alter_package_dropper_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
