# Generated by Django 5.2.1 on 2025-09-06 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_package_recipient_id_alter_package_recipient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User name associated with the service code', max_length=100)),
                ('code', models.CharField(help_text='Unique service code (e.g., 1234)', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Code',
                'verbose_name_plural': 'Service Codes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='enable_service_code_validation',
            field=models.BooleanField(default=False, help_text='Enable service code validation for critical operations'),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient_id',
            field=models.CharField(blank=True, help_text='Recipient ID (max 6 characters, e.g., kwe45, k1234s)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='packagehistory',
            name='service_code',
            field=models.CharField(blank=True, help_text='Service code used for validation', max_length=10, null=True),
        ),
    ]
