# Generated by Django 5.2.1 on 2025-09-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_servicecode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCode',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='enable_service_code_validation',
        ),
        migrations.RemoveField(
            model_name='packagehistory',
            name='service_code',
        ),
    ]
