# Generated by Django 5.2.1 on 2026-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delete_servicecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
