# Generated by Django 5.2.1 on 2026-01-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_package_picker_id'),
    ]

    operations = [
    ]
