# Generated by Django 5.2.1 on 2026-01-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_clear_picker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='picker_id',
            field=models.CharField(blank=True, help_text='Picker member number (max 6 characters)', max_length=20, null=True),
        ),
    ]
